### ISSUE TITLE
Έλεγχος δεδομένων του matlab

### ISSUE THREAD

**Issue by anagno** [anagno/PatternRecognition#2]
Κυριάκο, θυμάσαι πως επρεπε να μετατρέψουμε τα δεδομένα ;;; Τα έχω εξάγει σωστά ;;;

**Comment by kiriakosv** [comment]
Θα του ρίξω μια ματιά αύριο. Σου στέλνω σε mail τις σημειώσεις από την παράδοση που μας είπε
πως είναι περασμένα τα δεδομένα.

**Comment by anagno** [comment]
Νομίζω έτσι τα έκανα ... Τεσπα
