### ISSUE TITLE
5η ακηση

### ISSUE THREAD

**Issue by hybridkozo** [anagno/PatternRecognition#7]
Καλησπέρα, 

Η 5η άσκηση που πραγματοποιήσατε είναι σωστή γιατί έχουμε να υλοποιήσουμε την ίδια 

Ευχαριστώ

**Comment by anagno** [comment]
Αυτό είναι ερώτηση ή κατάφαση; Δεν σε καταλαβαίνω ...

**Comment by hybridkozo** [comment]
Ερώτηση είναι :D

**Comment by anagno** [comment]
Συνηδητοποιείς ότι αναφέρεσε σε μία άσκηση την οποία κάναμε ένα χρόνο πριν; 
Είσαι μόνος σου σε αυτό. Ανακάλυψε το ο ίδιος και πες και σε μας.

**Comment by hybridkozo** [comment]
Apla epeidi exw kanei to idio sas rwtaw an eixe apotelesma sthn eksetash. An theleis apantas giati ksereis an einai swsth h ulopoihsh apo ton bathmo pou pires apo thn ergasia.. An de theleis se euxaristw polu gia to xrono sou.

**Comment by anagno** [comment]
Την άσκηση αυτή την είχε απαντήσει σχεδόν μέσα στην τάξη και ο κώδικας είναι από τα παραδείγματα που μας είχε δώσει. Άρα, άμα δεν έχεις κάποια συγκεκριμένη ερώτηση, κάτσε ψάξε το και λίγο μόνος σου. Ο χρόνος μου δεν είναι για πέταμα. 
Τέλος για να μην μπλέκουμε και με αντιγραφές, το repository έχει πολύ συγκεκριμένη άδεια χρήσης και αναγράφεται στο αρχείο LICENSE. Άρα άμα θέλεις να χρησιμοποιήσεις υλικό φρόντισε να αναφέρεις την πηγή και δεν φέρω καμιά ευθύνη και υπευθυνότητα για τον τρόπο που χρησιμοποίησες το υλικό και για την ποιότητα του όπως αναγράφετε και στην άδεια.
